# Generated by Django 6.0.2 on 2026-02-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="hostels/main/",
                verbose_name="Головне фото готелю",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="rooms/previews/",
                verbose_name="Головне фото кімнати",
            ),
        ),
        migrations.CreateModel(
            name="HostelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="hostels/gallery/", verbose_name="Фото території"
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="booking.hostel",
                    ),
                ),
            ],
        ),
    ]
