# Generated by Django 6.0.2 on 2026-02-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_hostel_main_image_room_preview_hostelimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostel",
            name="adress",
        ),
        migrations.AddField(
            model_name="hostel",
            name="address",
            field=models.CharField(
                default="", max_length=255, verbose_name="Вулиця та номер будинку"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hostel",
            name="city",
            field=models.CharField(
                default="Київ", max_length=100, verbose_name="Місто"
            ),
        ),
    ]
