# Generated by Django 6.0.2 on 2026-04-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_hostel_adress_hostel_address_hostel_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активний"),
        ),
    ]
