# Generated by Django 6.0.2 on 2026-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_promoparticipant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="request_text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст заявки"),
        ),
    ]
