# Generated by Django 6.0.2 on 2026-02-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_booking_request_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="fullname",
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(default=1, max_length=50, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(default="", max_length=50, verbose_name="Прізвище"),
            preserve_default=False,
        ),
    ]
